# Generated by Django 4.0.1 on 2022-02-18 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_alter_group_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPlaceList',
            fields=[
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='place_list', serialize=False, to='groups.group')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('google_maps_id', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=7, default=0, max_digits=11)),
                ('longitude', models.DecimalField(decimal_places=7, default=0, max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_default', models.BooleanField(blank=True, default=False)),
                ('places', models.ManyToManyField(blank=True, related_name='place_lists', to='places.Place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_lists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place')),
                ('place_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='places.groupplacelist')),
                ('recommended_by', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
