# Generated by Django 4.0.1 on 2022-02-28 00:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[가-힣a-zA-Z0-9]*$')]),
        ),
    ]
